import { BarMenuConfig } from '@config/types/bar-menu-config';

const barMenuConfig: BarMenuConfig = {
  enabled: false,
  showInFooter: false,

  location: 'Benefactors Place',
  endTime: '10 PM',

  menu: [
    {
      category: 'Beer & Cider',
      items: [
        {
          name: 'Carlsberg',
          subtitle: null,
          unit_price: '£2.00',
          unit_quantity: '440ml ',
          line_1: null,
          line_2: null,
        },
        {
          name: 'Staropramen',
          subtitle: null,
          unit_price: '£3.00',
          unit_quantity: '440ml ',
          line_1: null,
          line_2: null,
        },
        {
          name: 'Inches',
          subtitle: null,
          unit_price: '£2.50',
          unit_quantity: '440ml ',
          line_1: null,
          line_2: null,
        },
        {
          name: 'Strongbow Strawberry',
          subtitle: null,
          unit_price: '£3.00',
          unit_quantity: '440ml ',
          line_1: null,
          line_2: null,
        },
        {
          name: "Lilley's",
          subtitle: 'Mango, Rhubarb, Fire Dancer',
          unit_price: '£4.00',
          unit_quantity: 'Pint',
          line_1: 'Half Pint £2.50',
          line_2: null,
        },
      ],
    },
    {
      category: 'Spirits',
      items: [
        {
          name: 'Absolut Vodka',
          subtitle: null,
          unit_price: '£2.50',
          unit_quantity: 'Single',
          line_1: 'Double £3.50',
          line_2: null,
        },
        {
          name: 'Spiced Rum',
          subtitle: 'Captain Morgans',
          unit_price: '£2.50',
          unit_quantity: 'Single',
          line_1: 'Double £3.50',
          line_2: null,
        },
        {
          name: 'Whiskey',
          subtitle: 'Buffalo Trace',
          unit_price: '£3.00',
          unit_quantity: 'Single',
          line_1: 'Double £4.00',
          line_2: null,
        },
        {
          name: 'Gin',
          subtitle: 'Gordons, Pink Gordons',
          unit_price: '£2.50',
          unit_quantity: 'Single',
          line_1: 'Double £3.50',
          line_2: null,
        },
        {
          name: 'Tequila',
          subtitle: 'Gold Jose Cuervo, Silver Jose Cuervo',
          unit_price: '£3.00',
          unit_quantity: 'Single',
          line_1: 'Double £4.00',
          line_2: null,
        },
        {
          name: 'Tequila Rose',
          subtitle: null,
          unit_price: '£2.50',
          unit_quantity: 'Single',
          line_1: '3 for £6',
          line_2: null,
        },
      ],
    },
    {
      category: 'Wine',
      items: [
        {
          name: 'Wine',
          subtitle: 'Red, White & Rose',
          unit_price: '£3.00',
          unit_quantity: '125ml',
          line_1: '250ml £5.00',
          line_2: null,
        },
        {
          name: 'Prosecco',
          subtitle: null,
          unit_price: '£4.00',
          unit_quantity: '125ml',
          line_1: null,
          line_2: null,
        },
      ],
    },
    {
      category: 'Specials',
      items: [
        {
          name: 'Jagerbomb',
          subtitle: null,
          unit_price: '£3.00',
          unit_quantity: null,
          line_1: '3 for £6',
          line_2: null,
        },
        {
          name: 'Purple',
          subtitle: null,
          unit_price: '£2.50',
          unit_quantity: null,
          line_1: null,
          line_2: null,
        },
        {
          name: 'Aperol Spritz',
          subtitle: null,
          unit_price: '£4.00',
          unit_quantity: null,
          line_1: null,
          line_2: null,
        },
        {
          name: 'W-Cocktail',
          subtitle: null,
          unit_price: '£4.50',
          unit_quantity: null,
          line_1: null,
          line_2: null,
        },
      ],
    },
    {
      category: 'Softs, Juice & Water',
      items: [
        {
          name: 'Soft Drinks',
          subtitle:
            '7-Up, Fanta, Diet Coke, Coca-Cola, Dr Pepper, Rubicon Sparkling Mango',
          unit_price: '£1.00',
          unit_quantity: '330ml ',
          line_1: null,
          line_2: null,
        },
        {
          name: 'Juice',
          subtitle: 'Apple, Orange, Cranberry, Pineapple',
          unit_price: '£1.00',
          unit_quantity: 'Half Pint',
          line_1: 'Pint £1.75',
          line_2: null,
        },
        {
          name: 'Redbull',
          subtitle: 'Redbull Original, Redbull Edition',
          unit_price: '£2.00',
          unit_quantity: null,
          line_1: '50p as mixer',
          line_2: null,
        },
        {
          name: 'Soda & Tonic',
          subtitle: 'Schwepps',
          unit_price: '£1.00',
          unit_quantity: null,
          line_1: null,
          line_2: null,
        },
        {
          name: 'Water',
          subtitle: null,
          unit_price: '£0.60',
          unit_quantity: 'Bottled',
          line_1: null,
          line_2: null,
        },
      ],
    },
  ],
};

export default barMenuConfig;
